package query.application.model;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;

import query.application.model.common.QueryMainAM;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 25 14:01:37 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QueryMainAMImpl extends ApplicationModuleImpl implements QueryMainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public QueryMainAMImpl() {
    }

    private void logmessages(String sDebug) {
        System.out.println(sDebug);
    }

    public ResultSet getSQLresult(String query) {
        
        String arr[] = query.split(" ", 2);

        String firstWord = arr[0];   //the
        
        
        if ("SELECT".equalsIgnoreCase(firstWord))
        {
        
        query = removeUserGenericError(query);

        ResultSet rs;
        try {
            rs = getDBTransaction().createStatement(0).executeQuery(query);
        } catch (SQLException e) {
            throw new JboException(e);

        }
        logmessages(rs.toString());
        return rs;
        }
        else {
            callStoredPackageProcedure(query);
            return null;
        }
    }
    
    public void callStoredPackageProcedure(String stmt) {
        System.out.println("callStoredPackageProcedure"+stmt);
        CallableStatement st = null;
        try {
            // 1. Create a JDBC CallabledStatement
            st = getDBTransaction().createCallableStatement(stmt, 0);
            // 2. Register the first bind variable for the return value
            st.executeUpdate();
        } catch (SQLException e) {
            throw new JboException(e);
        } finally {
            if (st != null) {
                try {
                    // 7. Close the statement
                    st.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
    private String removeUserGenericError(String query) {
        char lastChar = query.charAt(query.length() - 1);
        if (lastChar == ';') {
            query = query.substring(0, query.length() - 1);
        }
        return query;
    }
}

