package query.application.model;

import java.sql.ResultSet;
import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;

import query.application.model.common.QueryMainAM;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 25 14:01:37 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QueryMainAMImpl extends ApplicationModuleImpl implements QueryMainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public QueryMainAMImpl() {
    }

    private void logmessages(String sDebug) {
        System.out.println(sDebug);
    }

    public ResultSet getSQLresult(String query) {
        query = removeUserGenericError(query);

        ResultSet rs;
        try {
            rs = getDBTransaction().createStatement(0).executeQuery(query);
        } catch (SQLException e) {
            throw new JboException(e);

        }
        logmessages(rs.toString());
        return rs;
    }

    private String removeUserGenericError(String query) {
        char lastChar = query.charAt(query.length() - 1);
        if (lastChar == ';') {
            query = query.substring(0, query.length() - 1);
        }
        return query;
    }
}

