package query.application.model.common;

import java.sql.ResultSet;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 25 14:10:03 IST 2018
// ---------------------------------------------------------------------
public interface QueryMainAM extends ApplicationModule {
    ResultSet getSQLresult(String query);
}

